apiVersion: v1
kind: Service
metadata:
  name: web-microservice-svc
  annotations:   
    kubernetes.io/elb.class: union
    kubernetes.io/elb.enterpriseID: "72c72ff4-fc8b-4b1f-a687-44842e67b8f7"  # Optional parameter, Input Enterprise Project ID if it needs to be specify.
    kubernetes.io/elb.autocreate: 
        '{
            "type": "public",
            "bandwidth_name": "cce-bandwidth-web",
            "bandwidth_chargemode": "traffic",
            "bandwidth_size": 10,
            "bandwidth_sharetype": "PER",
            "eip_type": "5_bgp",
            "name": "cce-elb-web"
        }'
spec:
  type: LoadBalancer
  selector:
    app: v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
